<?php

declare(strict_types=1);

namespace OpenSim\Installer\Grid;

/**
 * Writes the config of a simulator and of its regions.
 *
 * The simulator config is the only file the launcher gives to OpenSimulator.
 * It carries what makes the simulator its own (ports, database, folders,
 * estate) and includes the architecture of the grid, which brings the services
 * of the grid (see GridShared). What it does not set comes from the defaults of
 * the core. Nothing may be written in the core, so every folder OpenSimulator
 * would use by default (relative to the core) is given here.
 */
final class SimConfig
{
    public function render(SimPlan $plan): string
    {
        $architecture = $plan->gridDir . '/config-include/' . ($plan->hypergrid ? 'GridHypergrid.ini' : 'Grid.ini');
        $slug = $plan->slug;

        $lines = [
            ";; Generated by opensim setup: simulator {$plan->simName} of the grid {$plan->gridName}",
            '',
            '[Const]',
            'BinDirectory = "' . $plan->binDir() . '"',
            'BaseHostname = "' . $plan->baseHostname . '"',
            'BaseURL = "http://' . $plan->baseHostname . '"',
            'PublicPort = ' . $plan->publicPort,
            'PrivatePort = ' . $plan->privatePort,
            'PrivURL = "${Const|BaseURL}"',
            'EtcDirectory = "' . $plan->gridDir . '"',
            'DataDirectory = "' . $plan->dataDirectory . '"',
            'CacheDirectory = "' . $plan->cacheDirectory . '"',
            'LogsDirectory = "' . $plan->logsDirectory . '"',
            '',
            '[Startup]',
            'regionload_regionsdir = "' . $plan->regionsDir() . '"',
            'RegistryLocation = "${Const|DataDirectory}/registry"',
            'PIDFile = "${Const|CacheDirectory}/' . $slug . '.pid"',
            'ConsoleHistoryFile = "${Const|LogsDirectory}/' . $slug . '.OpenSimConsoleHistory.txt"',
            'crash_dir = "${Const|CacheDirectory}/crashes"',
            'DecodedSculptMapPath = "${Const|CacheDirectory}/j2kDecodeCache"',
            '',
            '[Network]',
            'http_listener_port = ' . $plan->httpPort,
            'ExternalHostNameForLSL = "${Const|BaseHostname}"',
            '',
            '[DatabaseService]',
            'StorageProvider = "OpenSim.Data.MySQL.dll"',
            'ConnectionString = "' . $plan->connectionString() . '"',
            '',
            '[GridService]',
            'MapTileDirectory = "${Const|CacheDirectory}/maptiles"',
            '',
            '[DataSnapshot]',
            'snapshot_cache_directory = "${Const|CacheDirectory}/DataSnapshot"',
            '',
            '[YEngine]',
            'ScriptEnginesPath = "${Const|DataDirectory}/ScriptEngines"',
            '',
            '[Estates]',
            'DefaultEstateName = "' . $plan->estateName . '"',
            'DefaultEstateOwnerName = "' . $plan->estateOwner . '"',
            '',
            '[Architecture]',
            'Include-Architecture = "' . $architecture . '"',
            '',
        ];

        return implode("\n", $lines);
    }

    /** Write the config of the simulator, what it was before kept beside it. */
    public function write(SimPlan $plan): string
    {
        $path = $plan->iniPath();
        @mkdir(dirname($path), 0o755, true);
        if (is_file($path)) {
            @copy($path, "$path~");
        }
        file_put_contents($path, $this->render($plan));

        return $path;
    }

    /** The description of the first region of the simulator. */
    public function renderRegion(SimPlan $plan): string
    {
        return implode("\n", [
            ';; Generated by opensim setup',
            "[{$plan->regionName}]",
            "RegionUUID = {$plan->regionUuid}",
            "Location = {$plan->regionLocation}",
            "SizeX = {$plan->regionSize}",
            "SizeY = {$plan->regionSize}",
            "SizeZ = {$plan->regionSize}",
            'InternalAddress = 0.0.0.0',
            "InternalPort = {$plan->regionPort}",
            'ResolveAddress = False',
            'ExternalHostName = SYSTEMIP',
            'MaptileStaticUUID = 00000000-0000-0000-0000-000000000000',
            '',
        ]);
    }

    /** Write the region, unless a file of that name is there already. */
    public function writeRegion(SimPlan $plan): ?string
    {
        $path = $plan->regionIni();
        if (is_file($path)) {
            return null;
        }
        @mkdir(dirname($path), 0o755, true);
        file_put_contents($path, $this->renderRegion($plan));

        return $path;
    }
}
