<?php

namespace Deployer;

/**
 * Layout profiles: define target paths on the remote server.
 *
 * Layouts:
 *   debian — FHS-compliant system install (default)
 *   strict — project's own strict separation under /opt/opensim
 *   flat   — OpenSim default: everything under one directory
 *
 * Each layout writes a paths.conf to opensim_etc, which libexec/os-helpers reads
 * at runtime to resolve all paths without needing to know the layout itself.
 */

$layouts = [
    'debian' => [
        'opensim_bin' => '/usr/local/bin',
        'opensim_libexec' => '/usr/lib/opensim',
        'opensim_lib' => '/usr/local/lib/opensim',
        'opensim_share' => '/usr/share/opensim',
        'opensim_etc' => '/etc/opensim',
        'opensim_var' => '/var/lib/opensim',
        'opensim_core' => '/usr/share/opensim', // symlink → opensim-x.y.z
        'opensim_logs' => '/var/log/opensim',
        'opensim_cache' => '/var/cache/opensim',
        'opensim_data' => '/var/lib/opensim/data',
    ],
    'strict' => [
        'opensim_bin' => '/opt/opensim/bin',
        'opensim_libexec' => '/opt/opensim/libexec',
        'opensim_lib' => '/opt/opensim/lib',
        'opensim_share' => '/opt/opensim/share',
        'opensim_etc' => '/opt/opensim/etc',
        'opensim_var' => '/opt/opensim/var',
        'opensim_core' => '/opt/opensim/core',
        'opensim_logs' => '/opt/opensim/var/logs',
        'opensim_cache' => '/opt/opensim/var/cache',
        'opensim_data' => '/opt/opensim/var/data',
    ],
    'flat' => [
        'opensim_bin' => '/opt/opensim/bin',
        'opensim_libexec' => '/opt/opensim/bin',
        'opensim_lib' => '/opt/opensim/bin',
        'opensim_share' => '/opt/opensim',
        'opensim_etc' => '/opt/opensim/bin',
        'opensim_var' => '/opt/opensim/bin',
        'opensim_core' => '/opt/opensim',
        'opensim_logs' => '/opt/opensim/bin',
        'opensim_cache' => '/opt/opensim/bin',
        'opensim_data' => '/opt/opensim/bin',
    ],
];

// Register layout paths as Deployer variables; host-level `layout` overrides the default.
set('_layout_map', $layouts);

set('opensim_bin', fn() => _layoutVar('opensim_bin'));
set('opensim_libexec', fn() => _layoutVar('opensim_libexec'));
set('opensim_lib', fn() => _layoutVar('opensim_lib'));
set('opensim_share', fn() => _layoutVar('opensim_share'));
set('opensim_etc', fn() => _layoutVar('opensim_etc'));
set('opensim_var', fn() => _layoutVar('opensim_var'));
set('opensim_core', fn() => _layoutVar('opensim_core'));
set('opensim_logs', fn() => _layoutVar('opensim_logs'));
set('opensim_cache', fn() => _layoutVar('opensim_cache'));
set('opensim_data', fn() => _layoutVar('opensim_data'));

function _layoutVar(string $key): string
{
    $layout = get('layout', 'debian');
    $map = get('_layout_map');

    if (!isset($map[$layout])) {
        throw new \RuntimeException("Unknown layout '$layout'. Use: debian, strict, flat.");
    }

    return $map[$layout][$key] ?? throw new \RuntimeException("Layout '$layout' has no key '$key'.");
}

/**
 * Generate the paths.conf content for a given layout.
 * This file is written to opensim_etc on the remote and sourced by libexec/os-helpers.
 */
function layoutPathsConf(): string
{
    $vars = [
        'BIN' => get('opensim_bin'),
        'LIBEXEC' => get('opensim_libexec'),
        'LIB' => get('opensim_lib'),
        'SHARE' => get('opensim_share'),
        'EtcRoot' => get('opensim_etc'),
        'VAR' => get('opensim_var'),
        'CORE' => get('opensim_core'),
        'LOGS' => get('opensim_logs'),
        'CACHE' => get('opensim_cache'),
        'DATA' => get('opensim_data'),
    ];

    $lines = ['# Generated by Deployer — layout: ' . get('layout', 'debian')];
    foreach ($vars as $name => $value) {
        $lines[] = "$name=" . escapeshellarg($value);
    }
    $lines[] = '';

    return implode("\n", $lines);
}

/**
 * Write paths.conf to opensim_etc on the remote.
 */
task('layout:write-paths', function () {
    $etc = get('opensim_etc');
    $content = layoutPathsConf();
    run("mkdir -p $etc");
    run("cat > $etc/paths.conf <<'DEPLOYER_EOF'\n$content\nDEPLOYER_EOF");
})->desc('Write layout paths.conf to remote opensim_etc');
