#!/bin/bash

# Inspired by http://theoldschooldevops.com/2008/02/09/bash-ini-parser/
# and some other works
# Fixed ini_writer to include current values 
# and show more thant two per section

shopt -s compat42
[ ! "$TAB" ] && TAB="   "

ini_parser ()
{
    OLD_IFS=$IFS
    ini="$(<$1)"                # read the file
    ini="${ini//[/\[}"          # escape [
    ini="${ini//]/\]}"          # escape ]
    IFS=$'\n' && ini=( ${ini} ) # convert to line-array
    ini=( ${ini[*]//;*/} )      # remove comments with ;
    ini=( ${ini[*]/\    =/=} )  # remove tabs before =
    ini=( ${ini[*]/=\   /=} )   # remove tabs be =
    ini=( ${ini[*]/\ =\ /=} )   # remove anything with a space around =
    ini=( ${ini[*]/#\\[/\}$'\n'ini.section.} ) # set section prefix
    ini=( ${ini[*]/%\\]/ \(} )    # convert text2function (1)
    ini=( ${ini[*]/=/=\( } )    # convert item to array
    ini=( ${ini[*]/%/ \)} )     # close array parenthesis
    ini=( ${ini[*]/%\\ \)/ \\} ) # the multiline trick
    ini=( ${ini[*]/%\( \)/\(\) \{} ) # convert text2function (2)
    ini=( ${ini[*]/%\} \)/\}} ) # remove extra parenthesis
    ini[0]="" # remove first element
    ini[${#ini[*]} + 1]='}'    # add the last brace
    eval "$(echo "${ini[*]}")" # eval the result
    IFS=$OLDIFS
}
ini_fetchall ()
{
    OLD_IFS=$IFS
    IFS=' '$'\n'
    fun="$(declare -F)"
    fun="${fun//declare -f/}"
    for f in $fun; do
	[ "${f#ini.section}" == "${f}" ] && continue
        eval $f
    done
}
ini_writer ()
{
    IFS=' '$'\n'
    fun="$(declare -F)"
    fun="${fun//declare -f/}"
    for f in $fun; do
        [ "${f#ini.section}" == "${f}" ] && continue
	[ "$1" ] && [ "$f" != "ini.section.$1" ] && continue
        item="$(declare -f ${f})"
        item="${item##*\{}"
        item="${item%\}}"
#        item="${item//=*;/}"
#        vars="${item//=*/}"
        echo "[${f#ini.section.}]"
 	vars="$item"
	tmp=$(mktemp)
        for var in $vars; do
	    var="${var%=*}"
            echo "$INITAB"$var=\"${!var}\" | grep -v ');*=""'
        done > $tmp
	eval $f
	. $tmp
	rm -f $tmp
        for var in $vars; do
	    var="${var%=*}"
            echo "$TAB"$var=\"${!var}\" | grep -v ');*=""'
        done
	rm -f $TMP.saved
	echo
    done
    IFS=$OLDIFS
}
