#!/bin/bash

[ ! "$OPENSIM" ] && OPENSIM=opensim
[ ! "$PGM" ] && PGM=$(basename "$0")
[ ! "$TMP" ] && TMP=/tmp/$PGM.$$

if ! which realpath >/dev/null; then
  realpath() {
    readlink -f "$@" 2>/dev/null && return
    cd "$@" 2>/dev/null && pwd -P && return
  }
fi
echo $0

# echo ":$PATH:" | grep -q ":$BINDIR:" || export PATH=$PATH:$BINDIR
# [ ! "$LIB" ] && LIB=$BASEDIR/lib
BINDIR=$(dirname $(realpath "$0"))
BASEDIR=$(dirname "$BINDIR")
[ ! "$CONTRIB" ] && CONTRIB=$BASEDIR/contrib
echo BASEDIR $BASEDIR
. $CONTRIB/bash-helpers/helpers || echo "$PGM: Missing helpers library, run install.sh"

for etc in $BASEDIR/etc /etc/opensim ~/etc/opensim
do
    [ -d "$etc" ] && ETC=$etc
    [ -f "$etc/opensim.conf" ] && . $ETC/opensim.conf 2>/dev/null
done

[ ! "$LIB" ] && LIB=$BASEDIR/lib
[ ! "$VAR" ] && VAR=$BASEDIR/var
[ ! "$LOGS" ] && LOGS=$VAR/logs
[ ! "$CACHE" ] && CACHE=$VAR/cache
[ ! "$SRC" ] && SRC=$BASEDIR/src
[ ! "$CORE" ] && CORE=$BASEDIR/core
# [ ! "$OSBINDIR" ] && OSBINDIR="$CORE/opensim/bin"

OSBIN=$(
ls $OSBINDIR/bin/OpenSim.exe 2>/dev/null \
|| ls $CORE/*/bin/OpenSim.exe 2>/dev/null | head -1
)
[ "$OSBIN" ] \
&& log "$OSBIN found" && OSDIR=$(dirname $OSBIN) \
|| log 1 "OpenSim.exe not found, run install.sh"

osConsole() {
  [ ! "$2" ] && return
  osInstance=$1
  shift
  osCommand="$@"
  lr=$(printf "\n\b")
  pre=$(printf "\n\b")
  screen -S $osInstance -X stuff "$(echo "$pre$osCommand$lr")"
}
