#!/bin/bash

[ ! "$OPENSIM" ] && OPENSIM=core/opensim
[ ! "$PGM" ] && PGM=$(basename "$0")
[ ! "$TMP" ] && TMP=/tmp/$PGM.$$

if ! which realpath >/dev/null; then
  realpath() {
    readlink -f "$@" 2>/dev/null && return
    cd "$@" 2>/dev/null && pwd -P && return
  }
fi

# echo ":$PATH:" | grep -q ":$BINDIR:" || export PATH=$PATH:$BINDIR
# [ ! "$LIB" ] && LIB=$BASEDIR/lib
BINDIR=$(dirname $(realpath "$0"))
BASEDIR=$(dirname "$BINDIR")
[ ! "$CONTRIB" ] && CONTRIB=$BASEDIR/contrib
. $CONTRIB/bash-helpers/helpers || echo "$PGM: Missing helpers library, run install.sh"

LIB=$BASEDIR/lib
VAR=$BASEDIR/var
LOGS=$VAR/logs
CACHE=$VAR/cache
DATA=$VAR/data
SRC=$BASEDIR/src
CORE=$BASEDIR/core

for etc in $BASEDIR/etc /etc/opensim ~/etc/opensim
do
    [ -d "$etc" ] && ETC=$etc
    [ -f "$etc/opensim.conf" ] && . $ETC/opensim.conf 2>/dev/null
done

OSBIN=$(
ls $OSBINDIR/bin/OpenSim.exe 2>/dev/null \
|| ls $CORE/*/bin/OpenSim.exe 2>/dev/null | tail -1
)
[ "$OSBIN" ] \
&& log "$OSBIN found" && OSBINDIR=$(dirname $OSBIN) && OSDIR=$(dirname $OSBINDIR)\
|| log 1 "OpenSim.exe not found, run install.sh"

osConsole() {
  [ ! "$2" ] && return
  osInstance=$1
  shift
  osCommand="$@"
  lr=$(printf "\n\b")
  pre=$(printf "\n\b")
  screen -S $osInstance -X stuff "$(echo "$pre$osCommand$lr")"
}

cleanupIni() {
  [ "$1" ] || return
  [ -f "$1" ] || return
  cat "$1" | sed "s/^[[:blank:]]*//"
}

randomPassword() {
  < /dev/urandom tr -dc "A-Za-z0-9" | head -c32
}

crudget() {
  [ "$2" ] || return $?
  eval $(crudini --get --format=sh $1 $2  | sed -e "s/'\"/'/" -e "s/\"'/'/")
}

crudmerge() {
  [ -f "$2" ] || continue
  log merging $2 in $1
  cleanupIni $2 | sed "s/^Include-/IncludeDASH/" > $TMP.merge.ini
  crudini --merge $1 <$TMP.merge.ini || end $? $2 Merge failed
  # sed -i "s/^Include-/IncludeDASH/" $TMP.ini
}

cleanupIni4Prod() {
  [ "$1" ] || return
  sed -i "s/DASH/-/" $1
  crudini --get $1 > $TMP.sections
  cat $TMP.sections | while read section
  do
    crudini --get $1 $section | grep -qi [a-z] || crudini --del $1 "$section"
  done

}

testDatabaseConnection() {
  [ "$4" ] || return $?
  log "Testing database connection"
  DatabaseHost=$1
  DatabaseName=$2
  DatabaseUser=$3
  DatabasePassword=$4

  echo "" | mysql -h$DatabaseHost -u$DatabaseUser -p"$DatabasePassword" $DatabaseName
  if [ $? -ne 0 ]
  then
    echo "" | mysql -h$DatabaseHost -u$DatabaseUser -p"$DatabasePassword"
    if [ $? -ne 0 ]
    then
      createuser $DatabaseHost $DatabaseUser "$DatabasePassword" || return $?
    fi
    createDatabase $DatabaseHost $DatabaseUser $DatabaseName \
    && echo "" | mysql -h$DatabaseHost -u$DatabaseUser -p$DatabasePassword $DatabaseName \
    && log "Database OK" && return \
    || return $?
  fi
  log "Database Connection OK"
  return
}

createDatabaseUser() {
  [ "$3" ] || return $?
  yesno "Create database user $DatabaseUser on $DatabaseHost?" || return $?
  DatabaseHost=$1
  DatabaseUser=$2
  DatabasePassword=$3
  echo "CREATE USER $DatabaseUser IDENTIFIED BY '$DatabasePassword';" | mysql -h$DatabaseHost \
  return $?
}

createDatabase() {
  [ "$3" ] || return $?
  yesno "Create database $DatabaseName and grant rights to $DatabaseUser?" || return $?
  DatabaseHost=$1
  DatabaseUser=$2
  DatabaseName=$3
  echo "CREATE DATABASE $DatabaseName;"  | sudo mysql -h$DatabaseHost \
  && echo "GRANT ALL ON $DatabaseName.* TO $DatabaseUser;" | sudo mysql -h$DatabaseHost \
  && log "Database created"
  return $?
}
